services:
  djangoserver:
    container_name: backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3

  redis:
    image: redis:latest
    container_name: redis

  celery:
    container_name: celery
    build: .
    command: celery -A project worker -l INFO
    restart: always
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3

  celery-beat:
    container_name: celery-beat
    build: .
    command: celery -A project beat -l INFO
    restart: always
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
