# Generated by Django 5.1.1 on 2024-10-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('SAR', 'Saudi Riyal')], default='USD', max_length=3),
        ),
    ]
