# Generated by Django 5.1.1 on 2024-10-10 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sources',
            field=models.ManyToManyField(blank=True, to='exams.source'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'parent_category__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='exams.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='category',
            field=models.ForeignKey(limit_choices_to={'parent_category__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='exams.category'),
        ),
    ]
