# Generated by Django 5.1.1 on 2024-10-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_question_sources_alter_category_parent_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='best_revision',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='question',
            name='global_sequence',
        ),
        migrations.AddField(
            model_name='question',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_figure',
            field=models.ImageField(blank=True, upload_to='explanation_images'),
        ),
        migrations.AddField(
            model_name='question',
            name='figure',
            field=models.ImageField(blank=True, upload_to='question_images'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='reference',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Revision',
        ),
    ]
