# Generated by Django 5.1.1 on 2024-10-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_remove_question_best_revision_remove_choice_revision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='exam',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
