# Generated by Django 5.1.1 on 2024-10-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_subject_exam_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='question_order',
            field=models.JSONField(default=list),
        ),
    ]
