# Generated by Django 5.1.1 on 2024-10-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_session_completed_session_current_question_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='correct_answer_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='incorrect_answer_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='skipped_answer_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
