# Generated by Django 5.1.1 on 2024-10-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_session_correct_answer_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='unused_question_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
