# Generated by Django 5.1.1 on 2024-10-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_session_unused_question_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='number_of_questions',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
