# Generated by Django 5.1.1 on 2024-10-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_testcategory_testrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='labs',
            field=models.ManyToManyField(blank=True, to='exams.testcategory'),
        ),
    ]
