# Generated by Django 5.1.1 on 2024-10-22 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
