# Generated by Django 5.1.1 on 2024-10-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_alter_payment_acquirer_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
