# Generated by Django 5.1.1 on 2024-10-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_alter_payment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
