# Generated by Django 5.1.1 on 2024-10-23 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_usersubscription_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='acquirer_transaction_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='expires_on',
        ),
    ]
