# Generated by Django 5.1.1 on 2024-10-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_remove_payment_acquirer_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='active_paid_plan',
            field=models.BooleanField(default=False),
        ),
    ]
