# Generated by Django 5.1.1 on 2024-10-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0013_referralcode_referreduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='free_sessions',
            field=models.IntegerField(default=0),
        ),
    ]
